export const SIGN_IN = "SIGN_IN";
export const SIGN_OUT = "SIGN_OUT";
export const OPEN_SIGNIN_DIALOG = "OPEN_SIGNIN_DIALOG";
export const OPEN_SIGNUP_DIALOG = "OPEN_SIGNUP_DIALOG";
export const CLOSE_DIALOGS = "CLOSE_DIALOGS";
export const VERIFY_SESSION = "VERIFY_SESSION"